// Boots the complete app with a DOM adapter; checks real save/load and view events.
const fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),nodes=new Map(),local=new Map(),noop=()=>{};
function node(key=''){
 if(nodes.has(key))return nodes.get(key);
 const events={},attrs={},classes=new Set();
 const n={id:key,dataset:{},style:{setProperty:noop,removeProperty:noop},value:'',checked:false,disabled:false,hidden:false,innerHTML:'',textContent:'',options:{length:0},children:[],childNodes:[],scrollTop:0,isConnected:true,paused:true,volume:.5,
 classList:{add:(...s)=>s.forEach(x=>classes.add(x)),remove:(...s)=>s.forEach(x=>classes.delete(x)),contains:s=>classes.has(s),toggle:(s,on)=>{if(on===undefined)on=!classes.has(s);on?classes.add(s):classes.delete(s);return on}},
 addEventListener:(name,fn)=>{(events[name]||=[]).push(fn)},removeEventListener:noop,dispatch:(name,event)=>(events[name]||[]).forEach(fn=>fn(event)),listenerCount:name=>(events[name]||[]).length,
 setAttribute:(k,v)=>attrs[k]=v,getAttribute:k=>attrs[k]||'',removeAttribute:k=>delete attrs[k],querySelector:s=>node(key+' '+s),querySelectorAll:()=>[],closest:()=>null,contains:()=>false,
 appendChild:noop,insertBefore:noop,append:noop,prepend:noop,replaceChildren:noop,remove:noop,focus:noop,play:()=>Promise.resolve(),pause:noop,load:noop,getContext:()=>null,getBoundingClientRect:()=>({width:1672,height:941,x:0,y:0,left:0,right:1672,top:0,bottom:941}),cloneNode:()=>node(key+' clone'),matches:()=>false};
 nodes.set(key,n);n.parentElement=nodeParent;n.parentNode=nodeParent;return n;
}
const nodeParent={scrollTop:0,appendChild:noop,classList:{add:noop,remove:noop,toggle:noop}};
const context={console,btoa,atob,URLSearchParams,URL,Map,Set,WeakMap,WeakSet,Array,Object,String,Number,Boolean,Math,Date,JSON,RegExp,Promise,Intl,parseInt,parseFloat,isNaN,encodeURI,decodeURI,performance:{now:()=>Date.now()},setTimeout:()=>1,clearTimeout:noop,setInterval:()=>1,clearInterval:noop,requestAnimationFrame:()=>1,cancelAnimationFrame:noop,location:{search:''},navigator:{userAgent:'DOM-adapter'},innerWidth:1672,innerHeight:941,
 MutationObserver:class{observe(){}disconnect(){}},ResizeObserver:class{observe(){}disconnect(){}},IntersectionObserver:class{observe(){}disconnect(){}},
 localStorage:{getItem:k=>local.get(k)||null,setItem:(k,v)=>local.set(k,String(v)),removeItem:k=>local.delete(k)},Audio:function(){return node('audio')},Image:function(){return node('image')},
 document:{body:node('body'),head:node('head'),documentElement:node('html'),activeElement:null,hidden:false,getElementById:node,querySelector:s=>node(s),querySelectorAll:()=>[],addEventListener:noop,createElement:t=>node('created-'+t),createDocumentFragment:()=>node('fragment')},addEventListener:noop,removeEventListener:noop,matchMedia:()=>({matches:false,addEventListener:noop,removeEventListener:noop}),getComputedStyle:()=>({display:'block',visibility:'visible',getPropertyValue:()=>''})};
context.window=context;vm.createContext(context);
const scripts=['clubs.js','names.js','assets/manager/manager-assets.js','world-expansion.js','data/player-sprites.js','data/club-stadiums.js','training.js','training-ui.js','vendor/pako.min.js','save-codec.js','app.js'].filter(f=>fs.existsSync(path.join(root,f)));
for(const file of scripts){let source=fs.readFileSync(path.join(root,file),'utf8');if(file==='app.js')source=source.replace('  window.VELMORA_MANAGER_DEBUG={',`  window.trainingQA={v23TrainingData,v23SetTrainingPlayer,v23SetTrainingPreference,v23RenderTraining,processDailyPlayerUpdates,setCareerDate,getSquad,ensureLineup,initializeCareerLifecycle,currentCareerISO,setSquadView,saveCareerState,loadCareerState};\n  window.VELMORA_MANAGER_DEBUG={`);vm.runInContext(source,context,{filename:file})}
const D=context.VELMORA_MANAGER_DEBUG,Q=context.trainingQA;assert(D&&Q,'Full app boots');
const club=context.VELMORA_CLUBS.find(c=>c.id==='redwick');D.assignClubForTest(club);Q.initializeCareerLifecycle();
const initial=Q.v23TrainingData(),p=initial.rows[0].player,playerId=p.id,lineupBefore=JSON.stringify(Q.ensureLineup(club));
assert(initial.rows.length>6);assert(initial.rows.filter(r=>r.starter).length===3);assert(initial.rows.filter(r=>r.bench).length===3);
Q.v23SetTrainingPlayer(playerId,'drills');Q.v23SetTrainingPreference('automatic',true);Q.v23SetTrainingPreference('targetFitness',90);p.sharpness=42.5;assert(Q.saveCareerState());
const saveKey='velmora-manager-career-v32-slot-1',saved=JSON.parse(context.VelmoraSaveCodec.decode(local.get(saveKey)));assert(saved.version>=78);assert.equal(saved.careerPreferences.training.targetFitness,90);assert.equal(saved.squads[club.id].find(x=>x.id===playerId).sharpness,42.5);
p.sharpness=99;p.training.plan='recovery';assert(Q.loadCareerState());const loaded=Q.v23TrainingData(),again=loaded.rows.find(r=>r.player.id===playerId).player;assert.equal(again.sharpness,42.5);assert.equal(again.training.plan,'drills');assert.equal(again.training.mode,'manual');assert.equal(loaded.preferences.automatic,true);assert.equal(loaded.preferences.targetFitness,90);assert.equal(JSON.stringify(Q.ensureLineup(club)),lineupBefore);
// Legacy migration through the real serializer/deserializer, preserving clubs and fixtures.
const legacy=JSON.parse(context.VelmoraSaveCodec.decode(local.get(saveKey)));delete legacy.careerPreferences.training;for(const squad of Object.values(legacy.squads))for(const p of squad){delete p.training;delete p.sharpness;}legacy.version=73;local.set(saveKey,JSON.stringify(legacy));assert(Q.loadCareerState());const migrated=Q.v23TrainingData();assert.equal(migrated.preferences.automatic,false);assert(migrated.rows.every(r=>r.state.sharpness===70&&r.state.plan==='balanced'));assert.equal(migrated.next.opponent,loaded.next.opponent);
// Render actual HTML and dispatch the real change/click handlers; no progression on render.
const container=node('squadTrainingContent'),before=JSON.stringify(Q.getSquad(club));Q.v23RenderTraining();assert(container.innerHTML.includes('Ready for'));assert(container.innerHTML.includes('Assistant training'));assert(container.innerHTML.includes('data-tr-player'));assert.equal(JSON.stringify(Q.getSquad(club)),before);
const first=Q.v23TrainingData().rows[0].player;
container.dispatch('change',{target:{dataset:{trPlayer:first.id},value:'intensive',matches:()=>true}});assert.equal(first.training.plan,'intensive');
container.dispatch('change',{target:{dataset:{trPref:'automatic'},type:'checkbox',checked:true,matches:()=>true}});assert.equal(Q.v23TrainingData().preferences.automatic,true);assert.equal(first.training.mode,'manual');
Q.v23RenderTraining();Q.v23RenderTraining();assert.equal(container.listenerCount('change'),1);assert.equal(container.listenerCount('click'),1);
const today=Q.currentCareerISO(),tomorrow=context.VelmoraTraining.addDays(today,1);
const sharp=first.sharpness;Q.setCareerDate(tomorrow);Q.processDailyPlayerUpdates(tomorrow);assert(first.sharpness!==sharp);const once=JSON.stringify(Q.getSquad(club));Q.processDailyPlayerUpdates(tomorrow);assert.equal(JSON.stringify(Q.getSquad(club)),once);assert(Q.saveCareerState());assert(Q.loadCareerState());const afterReload=JSON.stringify(Q.getSquad(club));Q.processDailyPlayerUpdates(tomorrow);assert.equal(JSON.stringify(Q.getSquad(club)),afterReload);
console.log(JSON.stringify({status:'PASS',runtime:'Complete application with DOM adapter; no browser rendering',clubs:context.VELMORA_CLUBS.length,seniorPlayers:migrated.rows.length,checks:['complete app bootstrap','three starters plus three live substitutes with wider senior depth','actual save/load preserves sharpness, schedules and assistant targets','legacy v73 migration through actual loader','fixture and lineup preservation','real UI render, change events and one-time event binding','no gains from opening the screen','once-per-day progression survives save/reload']},null,2));
