const assert=require('node:assert/strict');
const {performance}=require('node:perf_hooks');
const {JSDOM}=require('jsdom');
const {runtime}=require('./career_test_runtime.cjs');
const r=runtime(),{q,d,context}=r;
const club=context.VELMORA_CLUBS.find(c=>c.abbr==='GRU');
d.assignClubForTest(club);q.initializeCareerLifecycle();
const timers=new Map(),frames=new Map();let next=1,encodes=0;
context.setTimeout=(fn,ms)=>{const id=next++;timers.set(id,{fn,ms});return id;};
context.clearTimeout=id=>timers.delete(id);
context.requestAnimationFrame=fn=>{const id=next++;frames.set(id,fn);return id;};
context.cancelAnimationFrame=id=>frames.delete(id);
const codec=context.VelmoraSaveCodec;
context.VelmoraSaveCodec={...codec,encode:json=>{encodes++;return codec.encode(json);}};
const initial=q.ensureLineup(club),a=initial.starter[0],b=initial.bench[0],c=initial.starter[1];
let started=performance.now();
q.swapLineupPlayers(club,a,b);q.refreshSeniorSquadUI({save:true});
q.swapLineupPlayers(club,b,c);q.refreshSeniorSquadUI({save:true});
const interactionMs=performance.now()-started;
assert.equal(encodes,0,'a swap must not serialize/compress a career on the input path');
assert.equal([...timers.values()].filter(t=>t.ms===900).length,1,'rapid swaps coalesce into one pending save');
const pendingFrames=[...frames.values()];frames.clear();pendingFrames.forEach(fn=>fn());
assert.equal(encodes,0,'animation-frame callbacks must remain free of full career saves');
const expected=JSON.parse(JSON.stringify(q.ensureLineup(club)));
const timer=[...timers.entries()].find(([,t])=>t.ms===900);timers.delete(timer[0]);timer[1].fn();
assert.equal(encodes,1,'one save after the quiet period');
const saved=[...r.local.entries()].find(([key])=>/^velmora-manager-career-v32-slot-\d$/.test(key));
assert(saved,'a durable save must be submitted');
assert.deepEqual(JSON.parse(codec.decode(saved[1])).lineups[club.id],expected,'saved lineup contains the latest swap, including bench and reserves');
q.swapLineupPlayers(club,a,c);q.refreshSeniorSquadUI({save:true});
assert(q.flushSquadSave(),'navigation/close flush succeeds');
assert.equal(encodes,2,'leaving the screen flushes outstanding changes');
assert.equal([...timers.values()].filter(t=>t.ms===900).length,0,'flush cancels a later duplicate save');
assert.deepEqual([75,76,81,82].map(q.playerTier),['bronze','silver','silver','gold']);
const dom=new JSDOM('<div id="cards"></div>'),mount=dom.window.document.getElementById('cards');
const originalCreate=context.document.createElement;
context.document.createElement=tag=>dom.window.document.createElement(tag);
q.patchSquadCards(mount,['<button data-player-id="A">A</button>','<button data-player-id="B">B</button>']);
const stable=mount.children[1];
q.patchSquadCards(mount,['<button data-player-id="C">C</button>','<button data-player-id="B">B</button>']);
assert.equal(mount.children[1],stable,'unaffected player keeps its DOM node and decoded portrait');
assert.equal(mount.children[0].dataset.playerId,'C','changed slot updates immediately');
q.patchSquadCards(mount,['<button data-player-id="C">C</button>']);
assert.equal(mount.children.length,1,'obsolete slots are removed');
context.document.createElement=originalCreate;
console.log(JSON.stringify({status:'PASS',twoSwapsAndRendersMs:Math.round(interactionMs),checks:['rating thresholds','coalesced saves','no compression before paint','saved latest lineup','flush before leaving','unaffected card reuse']},null,2));
