'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path');
const {JSDOM}=require('jsdom');
const {runtime}=require('./career_test_runtime.cjs');
const r=runtime(),{q,d,context}=r,club=context.VELMORA_CLUBS.find(c=>c.abbr==='GRU');
d.assignClubForTest(club);q.initializeCareerLifecycle();
const dom=new JSDOM(fs.readFileSync(path.resolve(__dirname,'../index.html'),'utf8'),{url:'http://localhost'});
context.document=dom.window.document;
const doc=dom.window.document;
q.renderSquad();
const startersBefore=Array.from(q.ensureLineup(club).starter),benchBefore=Array.from(q.ensureLineup(club).bench);
assert.equal(doc.querySelectorAll('#startingThreeShowcase [data-player-id]').length,3);
assert.equal(doc.querySelectorAll('#subsGrid [data-player-id]').length,5);
assert.equal(doc.querySelector('#squadReservePlaces').open,false,'vacant reserve places start collapsed');
q.beginSwap(benchBefore[0]);
assert.equal(doc.querySelector('#squadReservePlaces').open,true,'swap mode reveals vacant destinations');
const vacant=doc.querySelector('#reservesGrid button[data-drop-slot="0"]');
assert(vacant,'vacant destinations are keyboard-operable buttons');
vacant.click();
assert.equal(q.ensureLineup(club).reserve[0],benchBefore[0],'clicking an empty reserve moves the chosen player');
assert.equal(q.ensureLineup(club).bench[0],null,'source bench place becomes vacant');
q.beginSwap(benchBefore[0]);
doc.querySelector('#subsGrid button[data-drop-slot="0"]').click();
assert.deepEqual(Array.from(q.ensureLineup(club).bench),benchBefore,'vacant bench move restores the lineup');
q.beginSwap(benchBefore[0]);
doc.querySelector('#startingThreeShowcase [data-player-id]').click();
assert.equal(q.ensureLineup(club).starter[0],benchBefore[0],'occupied click swap remains supported');
assert.equal(q.ensureLineup(club).bench[0],startersBefore[0]);
q.flushSquadSave();
const saved=[...r.local.entries()].find(([key])=>/^velmora-manager-career-v32-slot-\d$/.test(key));
assert(saved,'squad changes produce a durable save');
let payload=JSON.parse(context.VelmoraSaveCodec.decode(saved[1]));
assert.equal(payload.lineups[club.id].starter[0],benchBefore[0],'persisted lineup includes the swap');
q.renderPlayerProfile();
doc.querySelector('[data-squad-profile-view="development"]').click();
const select=doc.querySelector('[data-squad-development]');
assert(select,'development tab has a real plan control');
select.value='Physical';select.dispatchEvent(new dom.window.Event('change',{bubbles:true}));
q.flushSquadSave();
payload=JSON.parse(context.VelmoraSaveCodec.decode([...r.local.entries()].find(([key])=>/^velmora-manager-career-v32-slot-\d$/.test(key))[1]));
assert.equal(payload.squads[club.id].find(p=>p.id===benchBefore[0]).developmentPlan,'Physical','development plan persists');
assert(q.v23SetTrainingPlayer(benchBefore[0],'recovery'),'existing training controls accept a schedule');
payload=JSON.parse(context.VelmoraSaveCodec.decode([...r.local.entries()].find(([key])=>/^velmora-manager-career-v32-slot-\d$/.test(key))[1]));
assert.equal(payload.squads[club.id].find(p=>p.id===benchBefore[0]).training.plan,'recovery','training schedule persists through the existing career system');
q.setSquadView('training');
assert(doc.querySelector('#squadTrainingContent select'),'training controls mount in the redesigned submenu');
q.setSquadView('overview');
assert.equal(doc.querySelector('#squadOverviewView').getAttribute('aria-hidden'),'false');
assert.equal(doc.querySelector('#seniorSquadView').getAttribute('aria-hidden'),'true');
assert.match(doc.querySelector('#squadOverviewView').textContent,/3 \/ 3/);
doc.querySelector('[data-overview-go="tactics"]').click();
assert(doc.querySelector('#squadTacticsView').classList.contains('is-active'),'overview links open the requested tool');
assert(!doc.querySelector('[data-v66-confirm]'),'autosave has no redundant confirm button');
console.log('Squad clubhouse: PASS — occupied and vacant swaps, durable lineup, development and training saves, overview navigation.');
dom.window.close();
